sudo : required

language : generic

services:
  -docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true docker-react npm run test --

after_success : 
  - echo "test success"
